name: Isaac
favicon: null
layout_spectrum: 0.7315329925622791
typography_spectrum: 0.7463667846750468
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors: []
  brandStrength: 0.3968834597617388
  lightness: 0.05123089696280658
  saturation: 0.7041199235245585
  rhythmicContrast: 0.2136383424513042
purpose: []
